# Generated by Django 3.0.3 on 2020-06-11 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0002_auto_20200611_2112'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='hnumber',
            new_name='House Number',
        ),
    ]
