# Generated by Django 3.0.3 on 2020-06-11 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0003_auto_20200611_2240'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='House Number',
            new_name='hnumber',
        ),
    ]
