# Generated by Django 3.0.3 on 2020-06-11 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0004_auto_20200611_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='lattitude',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='address',
            name='longitude',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
